apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.serviceName" .}}
  labels:
    app: jenkins
spec:
  type: {{ .Values.service.type}}
  ports:
  - port: 80
    name: web
    targetPort: 8080
  selector:
    app: jenkins